version: '3'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=help-desk-service
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./.db:/var/lib/postgresql/data:delegated
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5

  redis:
    image: redis:buster
    ports:
      - "6379:6379"

  help-desk-service:
    build:
      context: .
      dockerfile: "docker/Dockerfile.dev"
    env_file: .env
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always
