[tool.poetry]
name = "help-desk-service"
version = "0.1.0"
description = ""
authors = ["Ross Miller <ross.miller@digital.trade.gov.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.10.x"
Django = "^4.1.2"
djangorestframework = "^3.14.0"
Markdown = "^3.4.1"
django-model-utils = "^4.2.0"
zenpy = "^2.0.25"
django-multiselectfield = "^0.1.12"
psycopg2 = "^2.9.5"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
django-environ = "^0.9.0"
flake8 = "^5.0.4"
black = "^22.10.0"
isort = "^5.10.1"
mypy = "^0.982"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py37']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
